source: docs

title: Data Literacy Playground
description: Open Education Resource (OER) for 16-24 yr olds

author:
  name: DataLiteracyPlayground
  url: https://github.com/DataLiteracyPlayground/DataLiteracyPlayground

social:
  - network: github
    name: DataLiteracyPlayground
    url: https://github.com/DataLiteracyPlayground
  - network: twitter
    name: playground_data
    url: https://twitter.com/playground_data

collections:
  pages__me:
    output: true
    permalink: /me/:path/
  pages__society:
    name: Data and Society
    output: true
    permalink: /society/:path/
  pages__academy:
    name: Data and the Academy
    output: true
    permalink: /academy/:path/

defaults:
  # All Project Files
  -
    scope:
      path: ""
    values:
      background-image: alice-at-table.png

  # Categories (by collection)
  # Category index page frontmatter is assigned in the file itself
  -
    scope:
      path: ""
      type: "pages__me"
    values:
      layout: "category"
      category-color: var(--cat-theme--me)
      category-name: "Data and Me"
      category-slug: "me"
      background-image: "alice-caterpillar.jpg"
  -
    scope:
      path: ""
      type: "pages__society"
    values:
      layout: "category"
      category-color: "var(--cat-theme--society)"
      category-name: "Data and Society"
      category-slug: "society"
      background-image: "cards-tree.jpg"
  -
    scope:
      path: ""
      type: "pages__academy"
    values:
      layout: "category"
      category-color: "var(--cat-theme--academy)"
      category-name: "Data and the Academy"
      category-slug: "academy"
      background-image: "alice-lion-unicorn.jpg"
